### PR TITLE
PLANNER-2036: Port runLocally.sh VRP to work on macOS

### LINKED ISSUE #320: runLocally.sh doesn't work on macOS
```
$ ./runLocally.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
There is no last used VRP dir. Using the default.
VRP dir: /Users/jjarae/.optaweb-vehicle-routing
./runLocally.sh: line 24: declare: -l: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
VRP dir ‘�� does not exist. Do you want to create it now? [y/N]: ^C
```

### PR DESCRIPTION
**Pull request by yurloc**
### JIRA

https://issues.redhat.com/browse/PLANNER-2036

Fixes #320.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* for a <b>pull request build</b> please add comment: <b>Jenkins retest this</b>
* for a <b>full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* for a <b>compile downstream build</b> please add comment: <b>Jenkins run cdb</b>
* for a <b>full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* for an <b>upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

File: runOnOpenShift.sh [hunk 1]
```diff
@@ -163,7 +163,7 @@ echo
 echo -e "$summary"
 echo
 
-declare -l answer_continue # -l converts the value to lower case before it's assigned
+declare answer_continue # -l converts the value to lower case before it's assigned
```
Comment (Christopher-Chianelli) [inline runOnOpenShift.sh:166]: Misleading comment;
Might be able to use `shopt` to duplicate old behavior for "Y" https://stackoverflow.com/a/1728814

Comment (yurloc) [reply runOnOpenShift.sh:166]: Good catch, I'll remove the comment.

I've decided to no longer support the case insensitive response processing. If it requires anything more complex than the `-l` switch, it's not worth it.

File: runLocally.sh [hunk 2]
```diff
@@ -169,16 +149,52 @@ function download_menu() {
...
-  command -v xmllint > /dev/null 2>&1 || {
-    echo >&2 "ERROR: xmllint is not installed. Please install xmllint and retry."
-    exit 1
-  }
-
-  readarray -t region_names <<< "$(xmllint 2>>"$error_log" "$super_region_file" --html --xpath '//tr[@onmouseover]/td[1]/a/text()')"
-  readarray -t region_sub_hrefs <<< "$(xmllint 2>>"$error_log" "$super_region_file" --html --xpath '//tr[@onmouseover]/td[1]/a/@href' | sed 's/.*href="\(.*\)"/\1/')"
-  readarray -t region_osm_hrefs <<< "$(xmllint 2>>"$error_log" "$super_region_file" --html --xpath '//tr[@onmouseover]/td[2]/a/@href' | sed 's/.*href="\(.*\)"/\1/')"
-  readarray -t region_sizes <<< "$(xmllint 2>>"$error_log" "$super_region_file" --html --xpath '//tr[@onmouseover]/td[3]/text()' | sed 's/.*(\(.*\))/\1/')"
+  awk '
```
Comment (dupliaka) [inline runLocally.sh:152]: Could you please add a comment above to summarize what this awk should do?

File: runLocally.sh [hunk 3]
```diff
@@ -21,7 +21,7 @@ set -e
 shopt -s nullglob
 
 function confirm() {
-  declare -l answer # -l converts the value to lower-case before it's assigned
+  declare answer
   read -r -p "$1 [y/N]: " answer
```
[the remark this answers is not in the document]
Comment (yurloc) [reply runLocally.sh:25]: The capital "N" has nothing to do with the question whether the accepted answer is case sensitive or not. The capitalized letter signifies the default answer.

In other words, when you see `[y/N]` it should be clear what your options are and what the default/safe/recommended option is. Knowing that allows you to take a shortcut and just hit Enter without having to type the default answer.

I copied this behavior from the `dnf` package manager because I find it useful and I thought it's a convention for linux CLIs. But I might be wrong. The only source supporting this I could find retrospectively is this: https://ux.stackexchange.com/a/40445/43532.

File: runLocally.sh (hunk 2 above)
Comment (yurloc) [reply runLocally.sh:170]: Documentation added. Please check again.

File: runLocally.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (dupliaka) [reply runLocally.sh:25]: Sorry for that. The idea is pretty cool. Thanks for the explanation

**Review by dupliaka — APPROVED** [review]
